export default function Covid() {
    return (
        <div className='w-full'>
        <div className='terms block text-left mt-40 mx-auto w-[90%] sm:w-[75%]'>
            <p>Covid-19 Warning</p>
            <p>An inherent risk of exposure to COVID-19 exists in any place where people gather. COVID-19 is an extremely contagious disease that can lead to severe illness and death. You assume all risks, hazards, and dangers arising from or relating in any way to the risk of contracting COVID-19 or any other communicable disease or illness, or a bacteria, virus or other pathogen capable of causing a communicable disease or illness, whether occurring before, during, or after the event, however caused or contracted, and voluntarily waive all claims and potential claims against Secret Loft LLC relating to such risks.</p>

            <p>Purchase Policy</p>
            <p>You voluntarily assume all risks and danger incidental to the event for which the ticket is issued, whether occurring before, during or after the event, and you waive any claims for personal injury or death against us, management, facilities, artists, other participants, and all of our respective parents, affiliated entities, agents, officers, directors, owners and employees on behalf of yourself and any accompanying minor. You bear all risks of inclement weather. Event date and time are subject to change.</p>

            <p>Limitation of Liability</p>
            <p>In no event will we or our event organizers, suppliers, advertisers, and sponsors, be responsible or liable to you or anyone else for, and you hereby knowingly and expressly waive all rights to seek, direct, indirect, incidental, special, or consequential damages of any type, and any rights to have damages multiplied or otherwise increased, arising out of or in connection with any product or service purchased from secret loft llc, even if we have been advised of the possibility of such damages, and regardless of whether the claim is based upon any contract, tort, or other legal or equitable theory. Without limiting the foregoing, you expressly acknowledge and agree that we will have no liability or responsibility whatsoever for (a) any failure of another user of the venue to conform to the codes of conduct, (b) personal injury or property damage, of any nature whatsoever, whether arising in contract or in tort, resulting from your access to and use of our venue, (c) any errors, mistakes, inaccuracies, or omissions in any content, or (d) any lost, stolen, or damaged tickets, or the failure of the venue to honor a ticket. The limitations in this section will apply even if any limited remedy fails of its essential purpose. The allocation of risk between us is an essential element of the basis of the bargain between us. Our aggregate liability arising out of the terms or the use of the site will not exceed the greater of one hundred dollars ($100) or the amount you have paid us in the past twelve months. In no event will attorneys&apos; fees be awarded or recoverable. Our liability will be limited under this paragraph to the fullest extent permitted by applicable law, and the provisions of this paragraph will not apply to the extent applicable law permits the recovery of damages, attorneys&apos; fees, or costs otherwise prohibited under this paragraph.  The provisions of this paragraph that (a) prohibit damages to be multiplied or otherwise increased, (b) impose a damages limitation of the greater of one hundred dollars ($100) or the amount you have paid us in the past twelve months, and (c) prohibit the recovery of attorneys&apos; fees and costs, do not apply in certain states, including without limitation new jersey, to claims brought under statutes permitting such recovery.</p>
        </div>
        </div>
    )
}