import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from '../components/Nav'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          SILO
        </h1>
        <Nav />
        <div className={styles.splash}>
          <Image className={styles.splashImage} src="/splash.jpeg" width="100%" height="72%" layout="responsive" objectFit="contain">
          </Image>
        </div>
      </main>

      <Footer />
    </div>
  )
}
